# Generated by Django 5.1.7 on 2025-04-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
